<?php require("inc/cookiecheck.inc"); ?>
<!DOCTYPE html>
<html>
	     <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
       <meta name='viewport' content='width=device-width, initial-scale=1.0'>
	
<?php
 $maincssv=100;
 ?>
<head>

    <title> View your flashcards</title>
    <link type="text/css" rel="stylesheet" href="css/reset.css"/>
    <link type="text/css" rel="stylesheet" href="css/main.css?v=<?php echo $maincssv;?>"/>
    <script src="js/jquery-2.0.3.js"></script>
    <script src="js/jquery.cookie.js"></script>
    <script src="js/common.js"></script>
</head>
<body>
<?php
require("header.php");

if(isset($_GET['deckid'])){

    if(isset($_GET['status'])){
        $msg = '';
        switch($_GET['status']){
            case 'added':
                $msg = "Records successfully added!";
                break;
        }
        echo $msg."<br/>";
    }

    require("inc/getdeckname.inc");
    echo '<div id=title>'.
        ($_GET['deckid'] == 'all' ? "All Decks" : getDeckName($_GET['deckid'])) . "</div>";

    echo 'CEFR is generated by the system';
    echo '<table id="card-table">';
    
    class TableRows extends RecursiveIteratorIterator { 
        function __construct($it) { 
            parent::__construct($it, self::LEAVES_ONLY); 
        }
    
        function current() {
        	$tmpV=parent::current();
        	if (is_numeric($tmpV) && $tmpV<0 ) 
        	{
        		return "<td><font color='red'>" . parent::current(). "</font></td>";
        	} else if (is_numeric($tmpV) && $tmpV<0.5 )  
        	{
        		return "<td><font color='blue'>" . parent::current(). "</font></td>";
        	} else
        	{
                return "<td>" . parent::current(). "</td>";
        	}
        }
    
        function beginChildren() { 
            echo "<tr>"; 
        } 
    
        function endChildren() { 
            echo "</tr>" . "\n";
        } 
    } 
   
    require("inc/dbinfo.inc");
    $userid = $_SESSION['userid'];
    
    try {
        $conn = new PDO("mysql:host=$servername;dbname=$dbname", $dbusername, $dbpassword);
        $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        $tableCols = array();
        if( $_GET['deckid'] == 'all' ){
            $tableCols = array("Deck name","front","back");
            //$sql = "
            //    SELECT decks.name,front,back 
            //    FROM flashcards JOIN decks ON decks.deckid = flashcards.deckid
            //    WHERE userid=?
            //    ORDER BY decks.deckid, cardid ";
            $sql = "
                SELECT decks.name,front,back 
                FROM flashcards JOIN decks ON decks.deckid = flashcards.deckid
                
                ORDER BY decks.deckid, cardid ";    
            $stmt = $conn->prepare($sql); 
            $stmt->bindValue(1, $userid);
        }else{
            $tableCols = array("front","back");


            $sql = "
            select word,  back,  round(avg(choice),2) score , CEFR
            from  log_v_student v, flashcards f 
            where v.deckid=? and f.deckid=?
            and word=front
            group by word
            order by score
            ";

            $stmt = $conn->prepare($sql); 
            
           // $stmt->bindValue(1, $userid);
           // $stmt->bindValue(2, $_GET['deckid']);
           $stmt->bindValue(1, $_GET['deckid']);
           $stmt->bindValue(2, $_GET['deckid']);
        }

        
        $stmt->execute();
    
        // set the resulting array to associative
        $result = $stmt->setFetchMode(PDO::FETCH_ASSOC); 
    
        echo "<tr>";
        $displayCols=array("Word","Back", "Score","CEFR");
        foreach($displayCols as $colName){
            echo "<th>".$colName."</th>";
        }
        echo "</tr>";
        
        foreach(new TableRows(new RecursiveArrayIterator($stmt->fetchAll())) as $k=>$v) { 
            echo $v;
            
        }
        }
    catch(PDOException $e)
        {
        echo "Error: " . $e->getMessage();
        exit;
        }
    $conn = null;
    
    echo "</table>";
}
    echo "<button onclick='goBack()'>Go Back</button>";
require("footer.php");
?>

<script>
function goBack() {
  window.history.back();
}
</script>


</body>


